# Generated by Django 5.2.8 on 2025-11-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
